services:
  web: 
    image: alexsmirno/coderoute:latest
    container_name: coderoute
    build:
      dockerfile: ./Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres    
    image: postgres:latest
    environment:      
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin    
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/datavolumes
